create table monitor (
        id              int8 generated by default as identity,
        created_by      varchar(60)      NOT NULL,
        created_at      date             NOT NULL,
        display_size    int4             NOT NULL,
        height          int4             NOT NULL,
        length          int4             NOT NULL,
        updated_at      date,
        updated_by      varchar(60),
        width           int4             NOT NULL,
        workingplace_id int8             NOT NULL,
        primary key (id));


create table pc (
        id               int8 generated by default as identity,
        cpu_count        int4           NOT NULL,
        created_at       date           NOT NULL,
        created_by       varchar(60)    NOT NULL,
        heigth           int4           NOT NULL,
        length           int4           NOT NULL,
        ram_size         int4           NOT NULL,
        updated_at       date,
        updated_by       varchar(60),
        width            int4           NOT NULL,
        workingplace_id int8,
        primary key (id));


CREATE TABLE workingplace (
        id              int8 GENERATED BY DEFAULT AS IDENTITY ,
        city            varchar(60)     NOT NULL ,
        created_at      date            NOT NULL,
        created_by      varchar(60)     NOT NULL,
        name            varchar(60)     NOT NULL,
        updated_at      timestamp,
        updated_by      varchar(60),
        primary key (id));


ALTER TABLE IF EXISTS monitor
    ADD CONSTRAINT FK_monitor_workingplace
        FOREIGN KEY (workingplace_id)
            REFERENCES workingplace;


ALTER TABLE IF EXISTS pc
    ADD CONSTRAINT FK_pc_workingplace
        FOREIGN KEY (workingplace_id)
            REFERENCES workingplace;

