create table monitor (id int8 generated by default as identity, created_by varchar(60) not null, date date not null, display_size int4 not null, height int4 not null, length int4 not null, updated_at date, updated_by varchar(60), width int4 not null, workingplace_id int8 not null, primary key (id));
create table pc (id int8 generated by default as identity, cpu_count int4 not null, created_at date not null, created_by varchar(60) not null, heigth int4 not null, length int4 not null, ram_size int4 not null, updated_at date, updated_by varchar(60), width int4 not null, workingplace_id int8, primary key (id));
create table workingplace (id int8 generated by default as identity, city varchar(60) not null, created_at date not null, created_by varchar(60) not null, name varchar(60) not null, updated_at timestamp, updated_by varchar(60), primary key (id));
alter table if exists monitor add constraint FKagr8lhjhg50qlr4vah7nc4u4j foreign key (workingplace_id) references workingplace;
alter table if exists pc add constraint FK47yq2a65rj8xml73kd7v26q7v foreign key (workingplace_id) references workingplace;

